name: Articles auto translate
on:
  issues:
    types:
      - opened
jobs:
  ArticlesAutoTranslate:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    permissions:
      issues: write
      contents: write
    steps:
      # Check if the issue title starts with '[Auto]'. If not, exit the action.
      - name: Issue does not need to generate markdown
        if: ${{ !startsWith(github.event.issue.title, '[Auto]') }}
        shell: bash
        run: echo "This issue does not need to generate a markdown file." 1>&2; exit 1;

      # Check if the issue body is empty. If so, exit the action.
      - name: The description of the issue is empty
        if: ${{ !github.event.issue.body }}
        shell: bash
        run: echo "The description of the issue is empty." 1>&2; exit 1;

      - uses: actions/checkout@v3
      - name: Crawl pages and generate Markdown files
        id: fetch-webpage-to-markdown
        continue-on-error: true
        uses: freeCodeCamp-China/article-webpage-to-markdown-action@v2
        with:
          newsLink: '${{ github.event.issue.Body }}'
          ignoreSelector: '.ad-wrapper'
          markDownFilePath: './articles/_tmp/'
          githubToken: '${{ github.token }}'

      # Commit the local changes
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '${{ github.event.issue.title }}'
          file_pattern: articles/**/*.md
          commit_user_name: PageToMarkdown Bot
          commit_user_email: PageToMarkdown-bot@freeCodeCamp.org
